# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 08bf80bc514074d049d7637d19fc8822ea942db2d3fde98d40dfdb3554d2877dce96b88201a0b473526ab5aab51b9c7256b0a5ae630b383987eef7e5cbca883a

test:
  secret_key_base: d8ce4d7506b9495091253968baf978642051a0c92e5a5108fde5c82aa615f99d2986a397f6e1ad5ba3e05773ab5b60fee2af3e1ea9b133fe1c2d0206af9db53d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
